intents:
  app.open:
    patterns:
      - "відкрий {app:app_name}"
      - "відкриє {app:app_name}"
      - "запусти {app:app_name}"
      - "запустити {app:app_name}"
      - "open {app:app_name}"
    slots:
      app:
        type: app_name
        synonyms:
          chromium: ["google chrome", "хром", "браузер", "chrome"]
          https://youtube.com: ["ютуб", "youtube"]
          Telegram: ["telegram", "телеграм"]
          blender: ["blender", "блендер"]
          obsidian: ["obsidian", "обсидіан"]
          https://roblox.com: ["roblox", "роблокс"]
          discord: ["діскорд"]
          https://www.youtube.com/watch?v=7D4qgR3TsRc: ["Україна понад усе", "Україна"]
          prismlauncher: ["майнкрафт", "майн", "minecraft"]
  app.close:
    patterns:
      - "закрий {app:app_name}"
      - "вимкни {app:app_name}"
    slots:
      app:
        type: app_name
        synonyms:
          chromium: [ "google chrome", "хром", "chrome", "сайт" ]
          Telegram: [ "telegram", "телеграм" ]
          blender: [ "blender", "блендер" ]
          obsidian: [ "obsidian", "обсидіан" ]
          discord: [ "діскорд" ]
          prismlauncher: [ "майнкрафт", "майн", "minecraft" ]